### PR TITLE
Finaly added XML reporter

### PR DESCRIPTION
**Pull request by linslin**
Added XML reporter which was requested by a couple of users. Randomize your reports to integrate it into Continuous integration (for Example).

### CODE REVIEW

**Comment by linslin** [comment]
Usage:
  phpdcd [options] [--] [<values>]...

Arguments:
  values                             

Options:
      --names=NAMES                  A comma-separated list of file names to check [default: ["*.php"]]
      --names-exclude=NAMES-EXCLUDE  A comma-separated list of file names to exclude
      --exclude=EXCLUDE              Exclude a directory from code analysis (multiple values allowed)
      --log-xml=LOG-XML              Write result in XML format to file
      --recursive                    Report code as dead if it is only called by dead code
  -h, --help                         Display this help message
  -q, --quiet                        Do not output any message
  -V, --version                      Display this application version
      --ansi                         Force ANSI output
      --no-ansi                      Disable ANSI output
  -n, --no-interaction               Do not ask any interactive question
  -v|vv|vvv, --verbose               Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

**Comment by fluxsauce** [comment]
Hi there, it'd be nice to get this in there, what can we do to help get this accepted?

**Comment by linslin** [comment]
Hey @sebastianbergmann, could you bring some feedback?

**Comment by linslin** [comment]
@sebastianbergmann any news on this?

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.

**Comment by fluxsauce** [comment]
I'm sorry you feel that way, but I respect your decision. Thank you for the contributions.

It would be nice if this could be included in a final version, given that it's very short, community reviewed (it works), and adds functionality.

**Pull request closed without merging**
